name: GrieferGames-Reloaded
version: @version@
authors: [ NoJokeFNA, Niklas409 ]

main: net.griefergames.reloaded.GrieferGamesReloadedPlugin
softdepend: [ CloudNet-Perms, CloudNet-Bridge, LuckPerms, PermissionsEx, Essentials ]